//------------------------------------------------------------------------------
// <auto-generated>
//     Hand-maintained companion for Strings.resx / Strings.en.resx
// </auto-generated>
//------------------------------------------------------------------------------
namespace AxialSqlTools.Properties
{
    using System.ComponentModel;
    using System.Globalization;
    using System.Resources;

    public class Strings
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("AxialSqlTools.Properties.Strings", typeof(Strings).Assembly);
                }
                return resourceMan;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string Settings_WindowTitle => ResourceManager.GetString("Settings_WindowTitle", resourceCulture);
        public static string Settings_ToolWindowCaption => ResourceManager.GetString("Settings_ToolWindowCaption", resourceCulture);
        public static string Settings_Tab_General => ResourceManager.GetString("Settings_Tab_General", resourceCulture);
        public static string Settings_Tab_QueryTemplates => ResourceManager.GetString("Settings_Tab_QueryTemplates", resourceCulture);
        public static string Settings_Tab_CodeSnippets => ResourceManager.GetString("Settings_Tab_CodeSnippets", resourceCulture);
        public static string Settings_Tab_QueryHistory => ResourceManager.GetString("Settings_Tab_QueryHistory", resourceCulture);
        public static string Settings_Tab_CodeFormat => ResourceManager.GetString("Settings_Tab_CodeFormat", resourceCulture);
        public static string Settings_Tab_ExcelExport => ResourceManager.GetString("Settings_Tab_ExcelExport", resourceCulture);
        public static string Settings_Tab_GoogleSheets => ResourceManager.GetString("Settings_Tab_GoogleSheets", resourceCulture);
        public static string Settings_Tab_ConnectionColors => ResourceManager.GetString("Settings_Tab_ConnectionColors", resourceCulture);
        public static string Settings_Tab_Smtp => ResourceManager.GetString("Settings_Tab_Smtp", resourceCulture);
        public static string Settings_Tab_Updates => ResourceManager.GetString("Settings_Tab_Updates", resourceCulture);
        public static string Settings_LanguageLabel => ResourceManager.GetString("Settings_LanguageLabel", resourceCulture);
        public static string Settings_Language_Chinese => ResourceManager.GetString("Settings_Language_Chinese", resourceCulture);
        public static string Settings_Language_English => ResourceManager.GetString("Settings_Language_English", resourceCulture);
        public static string Settings_LanguageHint => ResourceManager.GetString("Settings_LanguageHint", resourceCulture);
        public static string Settings_SaveLanguage => ResourceManager.GetString("Settings_SaveLanguage", resourceCulture);
        public static string Settings_LanguageSaved => ResourceManager.GetString("Settings_LanguageSaved", resourceCulture);
        public static string Settings_Saved => ResourceManager.GetString("Settings_Saved", resourceCulture);
        public static string Common_Error => ResourceManager.GetString("Common_Error", resourceCulture);
        public static string Common_Done => ResourceManager.GetString("Common_Done", resourceCulture);
        public static string Menu_Toolbar => ResourceManager.GetString("Menu_Toolbar", resourceCulture);
        public static string Menu_QueryTemplates => ResourceManager.GetString("Menu_QueryTemplates", resourceCulture);
        public static string Menu_Tools => ResourceManager.GetString("Menu_Tools", resourceCulture);
        public static string Menu_FormatQuery => ResourceManager.GetString("Menu_FormatQuery", resourceCulture);
        public static string Menu_FormatQuery_Tooltip => ResourceManager.GetString("Menu_FormatQuery_Tooltip", resourceCulture);
        public static string Menu_ExportGridToExcel => ResourceManager.GetString("Menu_ExportGridToExcel", resourceCulture);
        public static string Menu_ExportGridToEmail => ResourceManager.GetString("Menu_ExportGridToEmail", resourceCulture);
        public static string Menu_ExportGridAsTempTable => ResourceManager.GetString("Menu_ExportGridAsTempTable", resourceCulture);
        public static string Menu_ExportGridToGoogleSheet => ResourceManager.GetString("Menu_ExportGridToGoogleSheet", resourceCulture);
        public static string Menu_ScriptDefinition => ResourceManager.GetString("Menu_ScriptDefinition", resourceCulture);
        public static string Menu_QuickSearch => ResourceManager.GetString("Menu_QuickSearch", resourceCulture);
        public static string Menu_SnippetManager => ResourceManager.GetString("Menu_SnippetManager", resourceCulture);
        public static string Menu_SelectCurrentStatement => ResourceManager.GetString("Menu_SelectCurrentStatement", resourceCulture);
        public static string Menu_SelectCurrentStatement_Tooltip => ResourceManager.GetString("Menu_SelectCurrentStatement_Tooltip", resourceCulture);
        public static string Menu_ToggleBlockComment => ResourceManager.GetString("Menu_ToggleBlockComment", resourceCulture);
        public static string Menu_ToggleBlockComment_Tooltip => ResourceManager.GetString("Menu_ToggleBlockComment_Tooltip", resourceCulture);
        public static string Menu_QueryHistory => ResourceManager.GetString("Menu_QueryHistory", resourceCulture);
        public static string Menu_StatisticsSummary => ResourceManager.GetString("Menu_StatisticsSummary", resourceCulture);
        public static string Menu_StatisticsSummary_Tooltip => ResourceManager.GetString("Menu_StatisticsSummary_Tooltip", resourceCulture);
        public static string Menu_HealthDashboardServer => ResourceManager.GetString("Menu_HealthDashboardServer", resourceCulture);
        public static string Menu_SqlServerBuilds => ResourceManager.GetString("Menu_SqlServerBuilds", resourceCulture);
        public static string Menu_DataTransfer => ResourceManager.GetString("Menu_DataTransfer", resourceCulture);
        public static string Menu_SyncToGitHub => ResourceManager.GetString("Menu_SyncToGitHub", resourceCulture);
        public static string Menu_RefreshTemplates => ResourceManager.GetString("Menu_RefreshTemplates", resourceCulture);
        public static string Menu_OpenTemplatesFolder => ResourceManager.GetString("Menu_OpenTemplatesFolder", resourceCulture);
        public static string Menu_Settings => ResourceManager.GetString("Menu_Settings", resourceCulture);
        public static string Menu_About => ResourceManager.GetString("Menu_About", resourceCulture);

        public static string Get(string name)
        {
            return ResourceManager.GetString(name, resourceCulture) ?? name;
        }
    }
}
